language: ruby
rvm:
  - 2.2.0
  - jruby-18mode
  - jruby-19mode
  - rbx-2
  - ruby-head
  - jruby-head
  - ree
env:
  - PUBLISHABLE_KEY="pk_test_kEbuoHxEkU9TXcLxMiqbO2wC"
  - SECRET_KEY="sk_test_HjgBPaq7P9RBbtyKejj3wwP7"