FORMAT: 1A

# SplitBill_Spring2015
API document for Split-Bill application.

# Group User Management [/user]
User profile related API.

## Login [/login]
User login API, set the login_type to set the login category.
* '1' for Normal Login
* '2' for Social App login

The email will be encrypted by AES if choose to login with social email.

### User Login [POST]
+ Request (application/json)

        { "email" : "sample@email.com",
          "password" : "ASDOWNSOQNSAODANSDSADA"
          "login_type" : 1
        }

+ Response 200 (application/json)

        { "id": 3, "token": "SADAJPDNANXZPSNA[WQSND[" }

+ Response 401 (application/json)

        { "msg": "Your email&password combination is invalid." }
        
+ Request (application/json)

        { "email" : "ASDJAKLSDNZPANQLONEXISADWQ" 
          "login_type" : 2
        } 

+ Response 200 (application/json)

        { "id": 3, "token": "SADAJPDNANXZPSNA[WQSND[" }

+ Response 401 (application/json)

        { "msg": "Email is invalid." }


## Email Sign Up [/signup]
Sign up for email login, user still could register if they used social login before.
The account will be merged.

### Sign Up [POST]
+ Request (application/json)

        { 
          "email" : "sample@email.com",
          "password" : "ASDOWNSOQNSAODANSDSADA"
        }

+ Response 200 (application/json)

        { "id": 3, "token": "SADAJPDNANXZPSNA[WQSND[" }

+ Response 401 (application/json)

        { "msg": "Account has already existed." }

