FORMAT: 1A

# SplitBill_Spring2015
API document for Split-Bill application.

# Group User Management [/user]
User profile related API.

## Email Login [/login]
Normal login with email and password.

### Login [POST]
+ Request (application/json)

        { "email" : "sample@email.com",
          "password" : "ASDOWNSOQNSAODANSDSADA"
        }

+ Response 200 (application/json)

        { "id": 3, "token": "SADAJPDNANXZPSNA[WQSND[" }

+ Response 401 (application/json)

        { "msg": "Your email&password combination is invalid." }

## Social Login [/login_social]
Login with social email, and the email has been encrypted by AES.

### Login [POST]
+ Request (application/json)

        { "email" : "ASDJAKLSDNZPANQLONEXISADWQ" } 

+ Response 200 (application/json)

        { "id": 3, "token": "SADAJPDNANXZPSNA[WQSND[" }

+ Response 401 (application/json)

        { "msg": "Email is invalid." }

## Email Sign Up [/signup]
Sign up for email login.

### Sign Up [POST]
+ Request (application/json)

        { 
          "email" : "sample@email.com",
          "password" : "ASDOWNSOQNSAODANSDSADA"
        }

+ Response 200 (application/json)

        { "id": 3, "token": "SADAJPDNANXZPSNA[WQSND[" }

+ Response 401 (application/json)

        { "msg": "Account has already existed." }

